on:
  pull_request:
    branches: 
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
          - ubuntu-24.04
          - windows-2025
    runs-on: ${{ matrix.os }}      
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup post check of known hosts file
        uses: pyTooling/Actions/with-post-step@9ceefdbf5dceae8c441fc393ed82344c7ca8bbdb # v3.1.1
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          main: |
            sh noop.sh
          post: |
            sh post_check.sh
      - name: Setup SSH key
        uses: ./
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          log-public-key: false
      - name: Check known hosts file
        shell: sh
        run: |
          sh check.sh
      - name: Install docker (Missing on MacOS)
        if: runner.os == 'macos'
        shell: bash
        run: |
          brew install --cask docker
      - name: Deploy over SSH
        shell: bash
        env:
          DOCKER_HOST: ${{ secrets.DOCKER_HOST }}
        run: |
          sh deploy.sh