on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        type: string
        description: New version for the release.
        required: true
jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
      - name: Tag release
        shell: sh
        env:
          RELEASE_VERSION: ${{ inputs.releaseVersion }}
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git tag -a "${RELEASE_VERSION}" -m "Release ${RELEASE_VERSION}"
          git push origin "${RELEASE_VERSION}"
          gh release create "${RELEASE_VERSION}" \
            --repo="$GITHUB_REPOSITORY" \
            --generate-notes \
            --latest \
            --title "${RELEASE_VERSION}"


